# Generated by Django 2.0.5 on 2018-05-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_restaurant_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantLocation',
        ),
    ]
