# Generated by Django 2.0.5 on 2018-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_restaurantlocation_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
