# Generated by Django 2.0.5 on 2018-06-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0008_restaurantlocation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='slug',
        ),
    ]
